### ISSUE TITLE
Add process user's selection missing

### ISSUE THREAD

**Issue by malerisch** [silentsignal/burp-piper#22] opened 2021-01-04 15:28 UTC
In v0.6.1, this enhancement was introduced: https://github.com/silentsignal/burp-piper/issues/16

However, when I use the latest version of Piper with the latest Burp 2020.12.1, I don't see it working any more.

Thanks.

**Comment by dnet** [comment] 2021-01-04 19:46
Works for me on this same config:

![shot](https://user-images.githubusercontent.com/163115/103572656-363a8880-4ecd-11eb-9f77-a21c59db4a56.png)

So it's definitely not a known bug, thus I need some help reproducing it on my machine:

 - What vendor and version of JRE are you running Burp with? In Burp, click `Help` and `Diagnostics` and scroll to `java.runtime.name` and `java.runtime.version` and copy the values next to them.
 - Where did you install Piper from? BApp store, GitHub release, your own build, etc.
 - If you're not using the default config, please export it to a Protobuf or YAML file.

You can paste these here or send it to me in an email to **vsza at vsza dot hu** and I'll try to reproduce it based on your input.

**Comment by malerisch** [comment] 2021-01-04 20:19
hi, thanks for your reply and for looking into this - my test was performed with the release from the bapp store - I noticed that  once I add a new command under the "Context Menu Items" or enable a disabled one (e.g. hexcurse), the issue is no longer there. So I guess that by "default" from the appstore, in my setup, the option to process selection would not appear because there were no items/commands that could be used with my selection?

**Comment by dnet** [comment] 2021-01-05 13:15
You're right, only those items appear in the menu that are capable of handling the selected text/data. If none, the submenu doesn't appear as it would be empty. This is intended behavior, so I'm closing this issue, but feel free to reply here if you have a better idea regarding UX.

**Closed by dnet** 2021-01-05 13:15 UTC

**Comment by malerisch** [comment] 2021-01-05 13:31
Thanks again and great work on this extension!
